USE cis251;
CREATE VIEW TRAINING_DISTRO AS
SELECT names.EMPLID, FIRST_NAME, LAST_NAME, EMAIL_ADDR
FROM names
	JOIN emailaddresses USING (EMPLID)
    JOIN job USING (EMPLID)
WHERE emailaddresses.PREF_EMAIL_FLAG = 'Y'
	AND job.POSITION_NBR IN (SELECT POSITION_NBR FROM positiondata);