USE cis251;
SELECT STATE, CITY, COUNT(DISTINCT names.EMPLID) as number_of_employees
FROM names
	JOIN addresses USING (EMPLID)
GROUP BY STATE, CITY
WITH ROLLUP
HAVING STATE IS NOT NULL AND CITY IS NOT NULL