USE cis251;
SELECT names.EMPLID, FULLNAME, ADDRESS1, ADDRESS2, CITY, STATE, EMAIL_ADDR, PHONE
FROM names
	JOIN addresses USING (EMPLID)
    JOIN emailaddresses USING (EMPLID)
    JOIN personalphone USING (EMPLID)
WHERE names.EMPLID = '201909318';